---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: golang
    tag: latest

inputs:
  - name: java-buildpack-memory-calculator

outputs:
  - name: artifactory

caches:
  - path: go-module-cache

run:
  path: java-buildpack-memory-calculator/ci/package.sh

params:
  VERSION: 4.1.0-BUILD-SNAPSHOT
